image:
  - macos-sonoma
  - ubuntu2204
  - windows2022

environment:
  GITHUB_TOKEN:
    secure: Kv9GbGkVnyPgbPrFY29V13NLA67SvJcU7JeDRZuhDbRRla9dU++3+F6VioJTIC

install:
  - python3 --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install flet
  - python3 -m pip install pyinstaller
  - export PATH="$HOME/Library/Python/3.9/bin:$PATH"
  - flet --version

build_script:
  - export PATH="$HOME/Library/Python/3.9/bin:$PATH"
  - if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == macos* ]]; then
      flet pack main.py --name "HH-Parser" --icon assets/icon.icns;
    else
      flet pack main.py --name "HH-Parser" --icon assets/icon.png;
    fi

artifacts:
  - path: dist/**
    name: HH-Parser

deploy:
  provider: GitHub
  auth_token:
    secure: Kv9GbGkVnyPgbPrFY29V13NLA67SvJcU7JeDRZuhDbRRla9dU++3+F6VioJTIC
  artifact: HH-Parser
  on:
    APPVEYOR_REPO_TAG: true